name: dbc-data-generator-108
base: core18
version: '0.1'
summary: dbc-data-generator-108
description: |
  dbc-data-generator-108.
grade: devel
confinement: devmode
architectures:
  - build-on: [amd64]
    run-on: [amd64]

apps:
  dbc-data-generator-108:
    command: bin/main.py
    daemon: simple

parts:
  dbc-data-generator-108:
    plugin: python
    python-version: python3
    source: .
    python-packages: [cantools, python-can, numpy]
  dbc:
    plugin: dump
    source: .
    filesets:
      exclude:
        - -bin
        - -build
        - -temp-build
        - -setup.py
    stage:
      - $exclude
    prime:
      - $exclude
